### ISSUE TITLE
/youtube, How to use?

### ISSUE THREAD

**Issue by gamersindo1223** [3052/platform#3]
Yeah pretty basic question tho

**Comment by 3052** [comment]
what did you try?

**Comment by gamersindo1223** [comment]
I mean, 
1. if it could bypass the age restriction limit,
2. how do I use this method to bypass it

**Comment by 3052** [comment]
it cant bypass the limit, it just uses your credentials instead - so if that's acceptable I can advise

**Comment by gamersindo1223** [comment]
ah I see, thanks
